---
monitoring_grafana_admin_group_name: Grafana Admins
monitoring_grafana_admin_bootstrap_username: admin
monitoring_grafana_allowlisted_groups: null
monitoring_agent_user_group: null
monitoring_agent_prometheus_endpoints: {}
monitoring_agent_postgres_instances: []
monitoring_agent_alloy_image: docker.io/grafana/alloy:latest
monitoring_grafana_image: docker.io/grafana/grafana:latest
monitoring_loki_allowlisted_groups: null
monitoring_loki_image: docker.io/grafana/loki:latest
monitoring_mimir_image: docker.io/grafana/mimir:latest
monitoring_mimir_additional_networks: []
monitoring_mimir_alertmanager_config_template: mimir-alertmanager-fallback-config.yml.j2
monitoring_mimir_allowlisted_groups: null
monitoring_mimir_log_level: info
monitoring_mimir_per_user_series_limit: 150000
monitoring_mimir_secrets: {}
monitoring_monitor_agent_user_group: null
